### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by andy-mc-donald** [fac-17/week5-chin-project#23]
You've got an accessibility score of 83, which is pretty good, but Lighthouse thinks the background and foreground colours don't have a sufficient contrast ratio.

**Comment by andy-mc-donald** [comment]
Actually sometimes the audit comes back with a score of 100, sometimes with 83 so  ¯\_(ツ)_/¯

**Comment by andy-mc-donald** [comment]
PS Firefox seems to say it doesn't like the contrast between the black writing on the blue background...

**Comment by reubengt** [comment]
did a css overhaul to fix this
