### ISSUE TITLE
hooray tests! and they pass :tada:

### ISSUE THREAD

**Issue by bantek89** [fac-17/week5-chin-project#27]
hooray tests! and they pass :tada: 

just a note, have you come across mocking api tests? It's great to see you testing the api response but we shouldn't really test the live api in our tests. If the api was down for some reason your tests would fail even though your code works!

_Originally posted by @bantek89 in https://github.com/fac-17/week5-chin-project/issues/19#issuecomment-517635070_

**Comment by reubengt** [comment]
will look into using nock to write API mock tests 👍
