### ISSUE TITLE
Dealing with api loading times

### ISSUE THREAD

**Issue by Oliversw** [fac-17/week5-chin-project#33]
Great project all!

When I first looked at the page I wasn't sure if it was working, but it turned out that the api was just taking a while to return.

One way to deal with this is to put some text (i.e. 'Loading ...') into the element that will eventually displaying the returned data, so that it is overwritten once the data arrives. 

Totally optional and more of a quality of life thing, but just wanted to mention it! :smile:

**Comment by reubengt** [comment]
@Oliversw we were thinking of two things..
1. an svg loading animation
2. to preload the api responses for our queries(since theres only a few) -  but this is cheating so we'll do a loading screen
